// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Omnimarket.Api.Data;

#nullable disable

namespace OmniMarket.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260503210521_Fase15PosVendaEstruturado")]
    partial class Fase15PosVendaEstruturado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Omni.Models.Entidades.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("TBL_CARRINHO", (string)null);
                });

            modelBuilder.Entity("Omni.Models.Entidades.ItemCarrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("TBL_ITEM_CARRINHO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Complemento")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("NomeEndereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("TipoLogradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TBL_ENDERECO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.AceiteUsuarioTermo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAceite")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificadorAceite")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("ResumoAceito")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("TermoPoliticaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("VersaoTermo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("IdentificadorAceite")
                        .IsUnique();

                    b.HasIndex("TermoPoliticaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TBL_ACEITE_USUARIO_TERMO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.AvaliacaoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<bool>("CompraVerificada")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("DtAtualizacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DtCriacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<int>("NotaLoja")
                        .HasColumnType("int");

                    b.Property<int>("NotaProduto")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<bool>("RecomendaProduto")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProdutoId", "PedidoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("TBL_AVALIACAO_PRODUTO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.CategoriaAtributoCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool>("Filtravel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresPermitidos")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId", "Slug")
                        .IsUnique();

                    b.ToTable("TBL_CATEGORIA_ATRIBUTO_CATALOGO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.CategoriaCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int?>("CategoriaPaiId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DtCriacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TBL_CATEGORIA_CATALOGO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.CondicaoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntervaloDias")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<decimal>("PercentualJuros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PossuiJuros")
                        .HasColumnType("bit");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorEntrada")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TBL_CONDICAO_PAGAMENTO", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntervaloDias = 0,
                            Nome = "A vista",
                            Observacao = "Pagamento integral em uma parcela.",
                            PercentualJuros = 0m,
                            PossuiJuros = false,
                            QuantidadeParcelas = 1,
                            ValorEntrada = 0m
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntervaloDias = 30,
                            Nome = "2x sem juros",
                            Observacao = "Parcelamento em 2 vezes sem juros.",
                            PercentualJuros = 0m,
                            PossuiJuros = false,
                            QuantidadeParcelas = 2,
                            ValorEntrada = 0m
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntervaloDias = 30,
                            Nome = "3x sem juros",
                            Observacao = "Parcelamento em 3 vezes sem juros.",
                            PercentualJuros = 0m,
                            PossuiJuros = false,
                            QuantidadeParcelas = 3,
                            ValorEntrada = 0m
                        },
                        new
                        {
                            Id = 4,
                            Ativa = false,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntervaloDias = 30,
                            Nome = "Pix parcelado (futuro)",
                            Observacao = "Condicao prevista para evolucao futura.",
                            PercentualJuros = 2.50m,
                            PossuiJuros = true,
                            QuantidadeParcelas = 2,
                            ValorEntrada = 0m
                        });
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.DocumentoFiscalVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("ProtocoloAutorizacao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Serie")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlDanfe")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("UrlXml")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChaveAcesso")
                        .IsUnique()
                        .HasFilter("[ChaveAcesso] IS NOT NULL");

                    b.HasIndex("LojaId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("VendaId")
                        .IsUnique();

                    b.HasIndex("VendedorId");

                    b.ToTable("TBL_DOCUMENTO_FISCAL_VENDA", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TBL_FORMA_PAGAMENTO", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Pix",
                            Observacao = "Pagamento instantaneo via Pix."
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Dinheiro",
                            Observacao = "Pagamento em dinheiro na retirada."
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Cartao de Debito",
                            Observacao = "Pagamento em cartao de debito."
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Cartao de Credito",
                            Observacao = "Pagamento em cartao de credito."
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Vale Refeicao",
                            Observacao = "Pagamento com vale refeicao."
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Vale Alimentacao",
                            Observacao = "Pagamento com vale alimentacao."
                        });
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.HistoricoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int?>("PlanoPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioResponsavelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PlanoPagamentoId");

                    b.HasIndex("UsuarioResponsavelId");

                    b.HasIndex("VendaId");

                    b.ToTable("TBL_HISTORICO_FINANCEIRO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.ItemPlanoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAutorizacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int?>("CondicaoPagamentoId")
                        .HasColumnType("int");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PlanoPagamentoId")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CondicaoPagamentoId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("PlanoPagamentoId");

                    b.ToTable("TBL_ITEM_PLANO_PAGAMENTO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.ItensPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("TBL_ITENS_PEDIDO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Loja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Cidade")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("DocumentoFiscal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTimeOffset?>("DtAtualizacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DtCriacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailContato")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<double>("MediaAvaliacao")
                        .HasColumnType("float");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("TelefoneContato")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("TipoDocumentoFiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalAvaliacoes")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.HasIndex("TipoDocumentoFiscal", "DocumentoFiscal")
                        .IsUnique();

                    b.ToTable("TBL_LOJA", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.LojaEntregaOpcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("CepFinal")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("CepInicial")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("CidadeCobertura")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PrazoMaxDias")
                        .HasColumnType("int");

                    b.Property<int>("PrazoMinDias")
                        .HasColumnType("int");

                    b.Property<decimal?>("RaioKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoEntregaId")
                        .HasColumnType("int");

                    b.Property<string>("UfCobertura")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("TBL_LOJA_ENTREGA_OPCAO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CepEntrega")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("CidadeEntrega")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("ComplementoEntrega")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeEnderecoEntrega")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("NumeroEntrega")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("StatusPedidosId")
                        .HasColumnType("int");

                    b.Property<int>("TipoEntregaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoLogradouroEntrega")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("UfEntrega")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalPedido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalProdutos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TBL_PEDIDO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.PedidoEntregaLoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoberturaResumo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("CondicoesAceitas")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("DataAceiteComprador")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAceiteVendedor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAtualizacaoStatus")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRecusaVendedor")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LojaEntregaOpcaoId")
                        .HasColumnType("int");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("NomeOpcao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("ObservacaoComprador")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("ObservacaoVendedor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("PrazoMaxDias")
                        .HasColumnType("int");

                    b.Property<int>("PrazoMinDias")
                        .HasColumnType("int");

                    b.Property<string>("StatusOperacional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEntregaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.HasIndex("PedidoId");

                    b.ToTable("TBL_PEDIDO_ENTREGA_LOJA", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.PlanoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayTransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("TBL_PLANO_PAGAMENTO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int?>("CategoriaCatalogoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTimeOffset?>("DtAtualizacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DtCriacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueVersao")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<double>("MediaAvaliacao")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProdutoPaiId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("StatusPublicacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAvaliacoes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaCatalogoId");

                    b.HasIndex("LojaId");

                    b.HasIndex("ProdutoPaiId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("TBL_PRODUTOS", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.ProdutoAtributoValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaAtributoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("ValorNormalizado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaAtributoId");

                    b.HasIndex("ProdutoId", "CategoriaAtributoId")
                        .IsUnique();

                    b.ToTable("TBL_PRODUTO_ATRIBUTO_VALOR", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.ProdutoMidia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTimeOffset>("DtCriacao")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("TBL_PRODUTOS_MIDIA", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.ReciboFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("MensagemLegal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("NumeroRecibo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int?>("PlanoPagamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("RepasseVendedorId")
                        .HasColumnType("int");

                    b.Property<string>("TextoAceiteVendedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorComissao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PlanoPagamentoId");

                    b.HasIndex("RepasseVendedorId");

                    b.HasIndex("VendaId");

                    b.ToTable("TBL_RECIBO_FINANCEIRO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.RepasseVendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEfetivaRepasse")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrevistaRepasse")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayPayoutId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("StatusRepasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorRepasse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("TBL_REPASSE_VENDEDOR", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.SolicitacaoPosVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar");

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("varchar");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar");

                    b.Property<int>("PedidoEntregaLojaId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CompradorId");

                    b.HasIndex("LojaId");

                    b.HasIndex("PedidoEntregaLojaId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("VendaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("TBL_SOLICITACAO_POS_VENDA", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.SolicitacaoPosVendaInteracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("varchar");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitacaoPosVendaId")
                        .HasColumnType("int");

                    b.Property<string>("StatusResultante")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorUsuarioId");

                    b.HasIndex("SolicitacaoPosVendaId");

                    b.ToTable("TBL_SOLICITACAO_POS_VENDA_INTERACAO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.TermoPolitica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TBL_TERMO_POLITICA", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.UsuarioCartaoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoValidade")
                        .HasColumnType("int");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<int>("MesValidade")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenGateway")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Ultimos4Digitos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenGateway")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "IsPrincipal")
                        .IsUnique()
                        .HasFilter("[IsPrincipal] = 1");

                    b.ToTable("TBL_USUARIO_CARTAO_PAGAMENTO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormulaComissaoAplicada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PercentualComissaoAplicado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StatusFinanceiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusVenda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorComissao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFixoComissaoAplicado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("VendedorId");

                    b.ToTable("TBL_VENDA", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.VendaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("PlanoPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("StatusFinanceiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorComissaoConsiderado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLiquidoConsiderado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPagoConsiderado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanoPagamentoId");

                    b.HasIndex("VendaId");

                    b.ToTable("TBL_VENDA_PAGAMENTO", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroE164")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TBL_TELEFONE", (string)null);
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceitouTermos")
                        .HasColumnType("bit");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("DataAceiteTermos")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConfirmacaoEmail")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("EmailConfirmacaoEnviadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmailConfirmacaoTokenExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailConfirmacaoTokenHash")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("RefreshTokenExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("RefreshTokenRevogadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResetSenhaSolicitadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResetSenhaTokenExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetSenhaTokenHash")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasFilter("[RefreshTokenHash] IS NOT NULL");

                    b.ToTable("TBL_USUARIO", (string)null);
                });

            modelBuilder.Entity("Omni.Models.Entidades.Carrinho", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Omni.Models.Entidades.ItemCarrinho", b =>
                {
                    b.HasOne("Omni.Models.Entidades.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Endereco", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.AceiteUsuarioTermo", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.TermoPolitica", "TermoPolitica")
                        .WithMany("Aceites")
                        .HasForeignKey("TermoPoliticaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TermoPolitica");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.AvaliacaoProduto", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.Loja", "Loja")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Produto", "Produto")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.CategoriaAtributoCatalogo", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.CategoriaCatalogo", "Categoria")
                        .WithMany("Atributos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.CategoriaCatalogo", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.CategoriaCatalogo", "CategoriaPai")
                        .WithMany("Filhas")
                        .HasForeignKey("CategoriaPaiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.DocumentoFiscalVenda", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Omnimarket.Api.Models.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Venda", "Venda")
                        .WithOne("DocumentoFiscal")
                        .HasForeignKey("Omnimarket.Api.Models.Entidades.DocumentoFiscalVenda", "VendaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Pedido");

                    b.Navigation("Venda");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.HistoricoFinanceiro", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Omnimarket.Api.Models.Entidades.PlanoPagamento", "PlanoPagamento")
                        .WithMany()
                        .HasForeignKey("PlanoPagamentoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Omnimarket.Api.Models.Usuario", "UsuarioResponsavel")
                        .WithMany()
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Omnimarket.Api.Models.Entidades.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Pedido");

                    b.Navigation("PlanoPagamento");

                    b.Navigation("UsuarioResponsavel");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.ItemPlanoPagamento", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.CondicaoPagamento", "CondicaoPagamento")
                        .WithMany("ItensPlanoPagamento")
                        .HasForeignKey("CondicaoPagamentoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Omnimarket.Api.Models.Entidades.FormaPagamento", "FormaPagamento")
                        .WithMany("ItensPlanoPagamento")
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.PlanoPagamento", "PlanoPagamento")
                        .WithMany("Itens")
                        .HasForeignKey("PlanoPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CondicaoPagamento");

                    b.Navigation("FormaPagamento");

                    b.Navigation("PlanoPagamento");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.ItensPedido", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Loja", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Usuario", "Usuario")
                        .WithOne("Loja")
                        .HasForeignKey("Omnimarket.Api.Models.Entidades.Loja", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.LojaEntregaOpcao", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.Loja", "Loja")
                        .WithMany("OpcoesEntrega")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Pedido", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.PedidoEntregaLoja", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Pedido", "Pedido")
                        .WithMany("Entregas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.PlanoPagamento", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Produto", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.CategoriaCatalogo", "CategoriaCatalogo")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaCatalogoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Omnimarket.Api.Models.Entidades.Loja", "Loja")
                        .WithMany("Produtos")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Produto", "ProdutoPai")
                        .WithMany("Variacoes")
                        .HasForeignKey("ProdutoPaiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CategoriaCatalogo");

                    b.Navigation("Loja");

                    b.Navigation("ProdutoPai");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.ProdutoAtributoValor", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.CategoriaAtributoCatalogo", "CategoriaAtributo")
                        .WithMany("ValoresProduto")
                        .HasForeignKey("CategoriaAtributoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Produto", "Produto")
                        .WithMany("Atributos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaAtributo");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.ProdutoMidia", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.Produto", "Produto")
                        .WithMany("Midias")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.ReciboFinanceiro", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.PlanoPagamento", "PlanoPagamento")
                        .WithMany()
                        .HasForeignKey("PlanoPagamentoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Omnimarket.Api.Models.Entidades.RepasseVendedor", "RepasseVendedor")
                        .WithMany()
                        .HasForeignKey("RepasseVendedorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Omnimarket.Api.Models.Entidades.Venda", "Venda")
                        .WithMany("Recibos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Pedido");

                    b.Navigation("PlanoPagamento");

                    b.Navigation("RepasseVendedor");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.RepasseVendedor", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.Venda", "Venda")
                        .WithMany("Repasses")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Venda");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.SolicitacaoPosVenda", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Usuario", "Comprador")
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.PedidoEntregaLoja", "PedidoEntregaLoja")
                        .WithMany()
                        .HasForeignKey("PedidoEntregaLojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Loja");

                    b.Navigation("Pedido");

                    b.Navigation("PedidoEntregaLoja");

                    b.Navigation("Venda");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.SolicitacaoPosVendaInteracao", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Usuario", "AutorUsuario")
                        .WithMany()
                        .HasForeignKey("AutorUsuarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Omnimarket.Api.Models.Entidades.SolicitacaoPosVenda", "SolicitacaoPosVenda")
                        .WithMany("Interacoes")
                        .HasForeignKey("SolicitacaoPosVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorUsuario");

                    b.Navigation("SolicitacaoPosVenda");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.UsuarioCartaoPagamento", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Usuario", "Usuario")
                        .WithMany("CartoesPagamento")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Venda", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.VendaPagamento", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Entidades.PlanoPagamento", "PlanoPagamento")
                        .WithMany("VendasPagamento")
                        .HasForeignKey("PlanoPagamentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Omnimarket.Api.Models.Entidades.Venda", "Venda")
                        .WithMany("VendaPagamentos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PlanoPagamento");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Telefone", b =>
                {
                    b.HasOne("Omnimarket.Api.Models.Usuario", "Usuario")
                        .WithMany("Telefones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Omni.Models.Entidades.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.CategoriaAtributoCatalogo", b =>
                {
                    b.Navigation("ValoresProduto");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.CategoriaCatalogo", b =>
                {
                    b.Navigation("Atributos");

                    b.Navigation("Filhas");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.CondicaoPagamento", b =>
                {
                    b.Navigation("ItensPlanoPagamento");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.FormaPagamento", b =>
                {
                    b.Navigation("ItensPlanoPagamento");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Loja", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("OpcoesEntrega");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Pedido", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.PlanoPagamento", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("VendasPagamento");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Produto", b =>
                {
                    b.Navigation("Atributos");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Midias");

                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.SolicitacaoPosVenda", b =>
                {
                    b.Navigation("Interacoes");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.TermoPolitica", b =>
                {
                    b.Navigation("Aceites");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Entidades.Venda", b =>
                {
                    b.Navigation("DocumentoFiscal");

                    b.Navigation("Recibos");

                    b.Navigation("Repasses");

                    b.Navigation("VendaPagamentos");
                });

            modelBuilder.Entity("Omnimarket.Api.Models.Usuario", b =>
                {
                    b.Navigation("CartoesPagamento");

                    b.Navigation("Enderecos");

                    b.Navigation("Loja");

                    b.Navigation("Pedidos");

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
