/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperarSenha'
import { Route as PerfilUsuarioRouteImport } from './routes/perfilUsuario'
import { Route as PaginaSucessoRouteImport } from './routes/paginaSucesso'
import { Route as PaginaPagamentoRouteImport } from './routes/paginaPagamento'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto/$id'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperarSenha',
  path: '/recuperarSenha',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilUsuarioRoute = PerfilUsuarioRouteImport.update({
  id: '/perfilUsuario',
  path: '/perfilUsuario',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginaSucessoRoute = PaginaSucessoRouteImport.update({
  id: '/paginaSucesso',
  path: '/paginaSucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginaPagamentoRoute = PaginaPagamentoRouteImport.update({
  id: '/paginaPagamento',
  path: '/paginaPagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/login': typeof LoginRoute
  '/paginaPagamento': typeof PaginaPagamentoRoute
  '/paginaSucesso': typeof PaginaSucessoRoute
  '/perfilUsuario': typeof PerfilUsuarioRoute
  '/recuperarSenha': typeof RecuperarSenhaRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/login': typeof LoginRoute
  '/paginaPagamento': typeof PaginaPagamentoRoute
  '/paginaSucesso': typeof PaginaSucessoRoute
  '/perfilUsuario': typeof PerfilUsuarioRoute
  '/recuperarSenha': typeof RecuperarSenhaRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/login': typeof LoginRoute
  '/paginaPagamento': typeof PaginaPagamentoRoute
  '/paginaSucesso': typeof PaginaSucessoRoute
  '/perfilUsuario': typeof PerfilUsuarioRoute
  '/recuperarSenha': typeof RecuperarSenhaRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/login'
    | '/paginaPagamento'
    | '/paginaSucesso'
    | '/perfilUsuario'
    | '/recuperarSenha'
    | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/login'
    | '/paginaPagamento'
    | '/paginaSucesso'
    | '/perfilUsuario'
    | '/recuperarSenha'
    | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/login'
    | '/paginaPagamento'
    | '/paginaSucesso'
    | '/perfilUsuario'
    | '/recuperarSenha'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  LoginRoute: typeof LoginRoute
  PaginaPagamentoRoute: typeof PaginaPagamentoRoute
  PaginaSucessoRoute: typeof PaginaSucessoRoute
  PerfilUsuarioRoute: typeof PerfilUsuarioRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperarSenha': {
      id: '/recuperarSenha'
      path: '/recuperarSenha'
      fullPath: '/recuperarSenha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfilUsuario': {
      id: '/perfilUsuario'
      path: '/perfilUsuario'
      fullPath: '/perfilUsuario'
      preLoaderRoute: typeof PerfilUsuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paginaSucesso': {
      id: '/paginaSucesso'
      path: '/paginaSucesso'
      fullPath: '/paginaSucesso'
      preLoaderRoute: typeof PaginaSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paginaPagamento': {
      id: '/paginaPagamento'
      path: '/paginaPagamento'
      fullPath: '/paginaPagamento'
      preLoaderRoute: typeof PaginaPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  LoginRoute: LoginRoute,
  PaginaPagamentoRoute: PaginaPagamentoRoute,
  PaginaSucessoRoute: PaginaSucessoRoute,
  PerfilUsuarioRoute: PerfilUsuarioRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
